### ISSUE TITLE
Opening mail or posts in another tab now defaults to no logged in user.

### ISSUE THREAD

**Issue by ikidd** [sheodox/alexandrite#103]
When I middle click to bring up a post or mail in a new tab, I have to go to Manage Accounts and choose my account, whereupon it then redirects me to the front page instead of the page I was on.  I hit Back twice and I'm on the page I originally brought up, and now I can do logged-in user things like upvote or read my messages.  This is the only account I have registered in Alexandrite.

I suspect the reason for this is that I recently cleared my browser cache and there is some cookie that isn't getting set.  I am using Firefox 126.  This does not seem to happen in Chrome.

a.Lemmy.world is using the latest version of Alexandrite.

**Comment by sheodox** [comment]
Hmmm, strange. I wonder if the logged out "guest" account is the default for your instance. Click "Switch Account" in the menu on the top right and see if your account is the one that's set as the default.

![image](https://github.com/sheodox/alexandrite/assets/3468630/b08b020b-6d68-41ca-bf0f-4f0db5b914df)

By the way I did see your post on Lemmy, I mostly lurk so don't have much post activity and haven't done much of any side project dev work in a while, but I still get notifications if you @ me there.

**Comment by ikidd** [comment]
It seemed to clear itself up a day or two later, no idea why.
