### ISSUE TITLE
View source markdown for a post

### ISSUE THREAD

**Issue by concur1** [sheodox/alexandrite#12]
In lemmy-ui it is possible to view the source markdown for a post/comment.

e.g. on this post:
![image](https://github.com/sheodox/alexandrite/assets/87602390/f9645322-8182-406f-8c8d-0f308f376b55) you can view the source by clicking this button: 
![image](https://github.com/sheodox/alexandrite/assets/87602390/cf18432a-134c-468d-b54d-03b75f783e78)

Could this be added to alexandrite at some point please?

**Comment by sheodox** [comment]
You could do this as of a few days ago on comments by clicking here:
![image](https://github.com/sheodox/alexandrite/assets/3468630/8556ad34-d98a-415a-99ef-ac8490b46e58)

And I just made a new button to do this on posts:
![image](https://github.com/sheodox/alexandrite/assets/3468630/9e7282b5-ae63-44f2-8441-2350b8f27a94)

**Comment by concur1** [comment]
Ahhh yes thank you! I was looking at a post with no content when I was trying to do this so that's why I didn't see it.

**Comment by sheodox** [comment]
You also didn't see it because that button didn't exist before 80 minutes ago when I added it in response to this ticket! ;)
