### ISSUE TITLE
Add cross post to alexandrite

### ISSUE THREAD

**Issue by concur1** [sheodox/alexandrite#13]
In lemmy-ui it is possible to cross-post a post to a different community.

e.g. on this post:
![image](https://github.com/sheodox/alexandrite/assets/87602390/f9645322-8182-406f-8c8d-0f308f376b55) you can cross-post by clicking this button: 
![image](https://github.com/sheodox/alexandrite/assets/87602390/09093719-efe0-4c4e-857f-d71cc326be23)

Could this be added to alexandrite at some point please?

**Comment by gon555551** [comment]
I second this request!! This would be really useful.

**Comment by sheodox** [comment]
This has been in for a while now, missed this issue so closing it now!
