### ISSUE TITLE
Feature request: Pin the left-hand side bar and favourite communities

### ISSUE THREAD

**Issue by davetansley** [sheodox/alexandrite#15]
It would be great if there was an option to pin the left-hand side bar in the open position, so that the list of communities was always visible.

As an extension to this, the ability to "star" communities, so that they appeared at the top of the list.

This would be useful for people who like to browse by community, rather than just a constant feed.

**Comment by sheodox** [comment]
I love the suggestions, I just added both! Let me know what you think.

There's a new checkbox in the settings
![image](https://github.com/sheodox/alexandrite/assets/3468630/50c22e9d-e06f-46c5-83c0-c2d7a9da86c2)

And hovering over the icon for a community now shows a star button to make it show in a separate Favorites list above subscriptions.
![image](https://github.com/sheodox/alexandrite/assets/3468630/9fbc167c-6da4-4aa7-b54c-cf84ab19a869)

**Comment by davetansley** [comment]
Perfect! It works exactly as I'd hoped!

**Comment by nanny07** [comment]
Is it just me or the even with the option checked I have to open it at least one time? If I hit refresh on the page it will start hidden and only if I open it then it will stay pinned
