### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by jSML4ThWwBID69YC** [sheodox/alexandrite#18]
May I ask what the code is licensed under? Is it free for anybody to use?

**Comment by sheodox** [comment]
I've been meaning to look into what the license needs to be. I've read it might need to be AGPL-3.0 because that's what [lemmy-js-client](https://github.com/LemmyNet/lemmy-js-client) is.

**Comment by sgriff96** [comment]
@sheodox I believe you're correct. Not super well versed in licensing but I believe we had to use AGPL-3.0 in [Memmy](https://github.com/Memmy-App/memmy/blob/main/LICENSE) for the same reason since we are using `lemmy-js-client`.

**Comment by sheodox** [comment]
Thanks! I see Voyager is also using that license. I've now updated the license in the repo.
