### ISSUE TITLE
Support Light mode

### ISSUE THREAD

**Issue by dtantono** [sheodox/alexandrite#19]
Hi 
Alexandrite looks good. But, not everyone likes dark mode. Is it possible to support light mode like original Lemmy?

**Comment by sheodox** [comment]
Yes I want to do this eventually, but It'll probably take a bit of time.

**Comment by sheodox** [comment]
I'm about to release a light mode and some more theming options! PR #59, you can test out the changes here: https://0-8-0.alexandrite.pages.dev/lemmy.world

It should detect your system's default theme, but you can set it to dark/light in the settings, and you're now also able to customize your theme's saturation, as well as the hues of links and up/down vote buttons.

Check it out and let me know what you think, and if you encounter any bugs.

Light mode (default colors):
![image](https://github.com/sheodox/alexandrite/assets/3468630/02fdd856-58bd-4590-99a4-804b8fcf68cd)

Light mode (customized):
![image](https://github.com/sheodox/alexandrite/assets/3468630/caf753ae-6b01-4c7a-bf96-3ce903b40631)

Dark mode (customized):
![image](https://github.com/sheodox/alexandrite/assets/3468630/0b341b7e-fdd8-476c-9fea-4457b5a04f00)

Settings:
![image](https://github.com/sheodox/alexandrite/assets/3468630/4ebb35f2-6806-4fe1-ab7a-ab4cbf7140e0)

Up/down votes colors:
![image](https://github.com/sheodox/alexandrite/assets/3468630/ab7687ad-bd05-45ec-a35e-b5c45b5538c2)

**Comment by sheodox** [comment]
Released!
