### ISSUE TITLE
Configurable Image Share Format

### ISSUE THREAD

**Issue by WestonHanners** [sheodox/alexandrite#21]
Right now all the links are defaulting to webp if I wanna copy the link to share the image, some apps like Facebook messenger don't support those. 

It would be nice if there was a way to set this to JPG.

**Comment by sheodox** [comment]
Just added this, try it out!

**Comment by sheodox** [comment]
Oops, forgot to mention that there's now a checkbox for whether it loads webp images in the settings now.

![image](https://github.com/sheodox/alexandrite/assets/3468630/b8a55b96-2713-47f1-bf70-3ded03e73d95)
