### ISSUE TITLE
(Feature request) Show text on the posts area

### ISSUE THREAD

**Issue by dtantono** [sheodox/alexandrite#23]
I love infinite scrolling and desktop focused appearance on Alexandrite. But, Like modern reddit or wefwef for Lemmy, it will be wonderful if we can see the glimpse of the text on the posts. Is it possible to make it appear like that?

**Comment by sheodox** [comment]
I've been wanting to make an alternate style for the posts in the feed soon, like what Voyager (wefwef) has with the larger images and bigger previews, I think showing some text there would look great. I'll add that when I get to working on the post style.

**Comment by sheodox** [comment]
I'm adding an alternate "Card" post layout that shows large (full height) images, and a preview of the post's content. In #51 which I'm merging soon.

**Comment by sheodox** [comment]
That has been released. Let me know what you think!

**Comment by dtantono** [comment]
to prevent wasted space on the desktop broweser. Is it possible to make it cover the whole screen?

**Comment by sheodox** [comment]
I've thought about it, but I'm not sure how to do it but make it look good.

The images on the cards all have a fixed width and take up as much height as the image wants, but I'd need to scale it all differently and have a max image height if the card layout was the full width otherwise you'd have gigantic images and it'd look bad and be inconvenient. Let me know if you have any ideas

**Comment by dtantono** [comment]
I usually use reddit enhancer to prevent wasted space to view the reddit posts on desktop browser and I hope alexandrite can do the same for Lemmy. What do you think?
![Untitled](https://github.com/sheodox/alexandrite/assets/29157187/729411c0-a187-4ca1-a6a4-0d9c1c814ef3)

**Comment by sheodox** [comment]
Ohh so you basically want the post preview on the list layout too. I could definitely add that as an option!

Do you like that the text is the full width of the page so more posts fit?

**Comment by dtantono** [comment]
yes that option would be great

**Comment by sheodox** [comment]
Just updated the site to add an option for that, here's an example:

![image](https://github.com/sheodox/alexandrite/assets/3468630/f5003aec-6675-4f69-8a2b-bdd79164523a)

Set it in the settings here with this new checkbox:

![image](https://github.com/sheodox/alexandrite/assets/3468630/ca0af25a-c06f-48db-984c-0f6e12ba90ca)

**Comment by dtantono** [comment]
That works. Thanks.
