### ISSUE TITLE
Readme for instance admin to host the project

### ISSUE THREAD

**Issue by subashz** [sheodox/alexandrite#24]
It would be cool to have some sorts of documentation to host this project.

**Comment by sheodox** [comment]
This is going to be my next project, should have it done this week hopefully!

**Comment by sheodox** [comment]
I have added a Dockerfile and some hosting instructions to the readme, plus support for a few configuration options.

They're in this branch: https://github.com/sheodox/alexandrite/tree/self-hosting

The published image is just slightly out of date but it shouldn't really matter much, as I switched publish to only run on pushes to the main branch so it stopped publishing updates until I merge that PR. You're welcome to try it out and let me know how it goes!
