### ISSUE TITLE
Loader stuck when clicking back button after navigating to external pages

### ISSUE THREAD

**Issue by veloxy** [sheodox/alexandrite#38]
When click on an external link a loader is shown while the page is loading. When on the next page and clicking the back button,the loader is still there and wont go away, forcing you to reload the page (and suddenly seeing a completely different view too)

![](https://i.imgur.com/f5RHCY0.gif)

Expected behavior: No loader when navigation back to the lemmy page.

**Comment by sheodox** [comment]
I could never replicate this issue, but I think this should be fixed by a change I made in #51 to not show the loading overlay when you're navigating away from the site.

**Comment by sheodox** [comment]
Fix has been released, let me know if it's fixed for you.

**Comment by asimons04** [comment]
I ran into this issue a few times, but can no longer replicate it.  External links seem to open in new tabs now (which I really like), so the issue may have become moot.

**Comment by sheodox** [comment]
If someone makes a post with a URL, that URL will open in a new tab (and always has) but the links in markdown (post text, comments, sidebars) all open in the same tab. I want to make everything that doesn't get rewritten as an Alexandrite link also open in new tabs but just haven't gotten around to that.

Anyways I'm going to close this!
