### ISSUE TITLE
Keyboard focus after loading home page

### ISSUE THREAD

**Issue by janvkn** [sheodox/alexandrite#41]
When you load the home page of the app (i.e. https://alexandrite.app/) the list with lemmy posts does not appear to have keyboard focus. This makes it impossible to scroll through the list with the keyboard using `PageUp`, `PageDown` and the arrow keys.

To be able to scroll the post list with the keyboard, you first have to click on an empty part of the post list, or press `TAB` about 15 times.

It would be better if the post list received the keyboard focus automatically, just like it is on the default lemmy site, or kbin, or r***it.

**Comment by sheodox** [comment]
This should be fixed now!

**Comment by janvkn** [comment]
I can confirm, keyboard navigation works immediately now. Thanks!
