### ISSUE TITLE
Tooltip on the reply button won't disappear

### ISSUE THREAD

**Issue by janvkn** [sheodox/alexandrite#42]
When you reply to a comment, the tooltip of the reply button pops up and doesn't disappear, obscuring part of the message.

![image](https://github.com/sheodox/alexandrite/assets/31570685/661c164a-2414-41ec-803b-a3023017bc99)

**Comment by sheodox** [comment]
Which browser do you have? Someone else has told me this happens but I've never seen it in Firefox.

**Comment by janvkn** [comment]
I'm using Chrome and it happens on Chromium too. I can confirm that it doesn't happen on Firefox.

**Comment by sheodox** [comment]
Fix for this is on alexandrite.app now!
