### ISSUE TITLE
Third (3rd) item of bullet list doesn't display

### ISSUE THREAD

**Issue by gon555551** [sheodox/alexandrite#43]
When using a Mardown bullet list, as shown below...

```
This is a list:
- Item 1
- Item 2
- Item 3
- Item 4
```
This is a list:
- Item 1
- Item 2
- Item 3
- Item 4

...The 3rd item doesn't display. This is true for both posts and the preview function.

**How to reproduce:**  
Start a new post and make a bullet list with 3 or more items. The 3rd item won't display on the preview, and when you *actually* post, you will not be able to see the 3rd item.

**What I'm using:**  
I'm browsing via [Alexandrite.app](https://alexandrite.app/), not any self-hosted version on any instance.

**Screeshots:**  
![The bug in preview, the 3rd item doesn't display.](https://i.postimg.cc/hPhcGmk0/Captura-de-ecr-2023-08-03-134407.png)

Example post: [https://alexandrite.app/lemmy.world/post/2578599](https://alexandrite.app/lemmy.world/post/2578599)  
![The bug in the post itself. The 3rd item doesn't display.](https://i.postimg.cc/sD3KP9jp/Captura-de-ecr-2023-08-03-134648.png)

This doesn't happen if seeing the post through a regular Lemmy WebUI.  
Example post: [https://lemmy.world/post/2578599](https://lemmy.world/post/2578599)  
![The bug doesn't happen if seeing the post from the standard Lemy WebUI. The 3rd item displays.](https://i.postimg.cc/sxhsDd8R/Captura-de-ecr-2023-08-03-134928.png)

**Comment by sheodox** [comment]
That is really strange! I haven't been able to replicate this though. The post you linked looks normal to me. Does it look the same in other browsers or with extensions disabled?

**Comment by gon555551** [comment]
Oh!!! No!!! 

I'm on Firefox with uBlock Origin. Might be my settings and blocked elements, since turning uBlock off returns the 3rd item... I'll look into it more.

**Comment by sheodox** [comment]
Ok, I'm going to assume it was that then, closing this! :)
