### ISSUE TITLE
Feature Request: Add an option for card-view like new Reddit.

### ISSUE THREAD

**Issue by YousufSSyed** [sheodox/alexandrite#46]

**Comment by sheodox** [comment]
Good timing, I actually have been working on this over the weekend! I'm adding "Card" and "Compact" post layouts for the feed. 

Here's a screenshot, still have some things to add (embedded link text, some of the post's body text).

I haven't actually used the card layout for reddit, so I'm just basing things off of Sync.

Anyways, let me know what you think:
![image](https://github.com/sheodox/alexandrite/assets/3468630/f4c3139b-d9a5-41dc-a243-fdf4c65323c8)

**Comment by YousufSSyed** [comment]
I'd want to actually try it out first, is there a way to test the newest commits to Alexandrite without installing it on my machine or something? Would that take work for you to setup?

And I think you should add a setting for views right next to the post sorting dropdown.

**Comment by sheodox** [comment]
I'll make a PR soon, and there will be a couple links from Cloudflare/Vercel bots that will post a link to that version of the site.

**Comment by sheodox** [comment]
Here's a demo link, let me know what you think! Check out the settings page for the new post layout options.

https://post-layouts.alexandrite.pages.dev/

**Comment by YousufSSyed** [comment]
Alright I took a look, and I'd highly recommend making the card view look more like Reddit's with the community, title, username, and timestamp at the top, and the rest at the bottom. This would make Lemmy much more suitable for users switching from Reddit. Most Reddit users use new reddit.
<img width="665" alt="Screenshot 2023-08-08 at 4 05 45 AM" src="https://github.com/sheodox/alexandrite/assets/42646062/e55ac03c-6ef4-4caf-9206-277f575c1eb3">

**Comment by sheodox** [comment]
I've moved the image down and added some more stuff (first few lines of the post's body/embed description). Going to merge this soon!

**Comment by sheodox** [comment]
It's in!

**Comment by YousufSSyed** [comment]
@sheodox Have you considered adding a "join" button next to the community name like the image above? That would be nice.

Something that would be really benefitial is if the vote buttons were on the top left corner like on reddit and laid out like the image above. It would make the learning curve for Reddit users much smaller. When scrolling through new Reddit, I put my cursors where the arrow is and scroll down, keeping it in the same general area so I can quickly vote.

**Comment by sheodox** [comment]
The join button is a good idea. I might do something like that in the future.

I don't plan on moving the vote buttons though. They just fit the best there in my current design, and they're much easier to reach on the bottom right, than the top left on mobile (which I'm working towards supporting). I'm currently working on adding some basic hotkey support which I will probably release today, then you can use some hotkeys similar to RES, so you'd be able to use `j` and `k` to scroll through posts, and `a` and `z` to up/down vote them.

**Comment by YousufSSyed** [comment]
Can you make the UIs vary a little on desktop and on mobile? Perhaps put the vote buttons on the top left on desktop, and keep them on the bottom on mobile?

**Comment by YousufSSyed** [comment]
At the very least, I think you should put the vote buttons on the left side with all the other buttons, so you don't have to move the mouse left and right to do things.
