### ISSUE TITLE
"Scroll to top" button jitters

### ISSUE THREAD

**Issue by Erikatharsis** [sheodox/alexandrite#48]
Firefox, Windows 10, for what it's worth.

Hovering the mouse cursor over the "scroll to top" button causes a set of horizontal and vertical scroll bars to rapidly appear and disappear. This causes the "scroll to top" button to jitter diagonally. I have opted to hide the "scroll to top" button using a uBlock Origin cosmetic filter (alexandrite.app##.svelte-8424c7.gap-2.f-row.floating-nav-container) since I personally felt like this button was visual clutter anyways.

A simple solution to both the issue of visual clutter as well as button jittering might be to move the "scroll to top" button to the upper bar. There is a lot of blank space on either side of the search bar.

**Comment by sheodox** [comment]
I changed how tooltips are positioned so once #51 is merged this should stop happening.

I might change that button to only show if you start scrolling back up in the future though, that'd be nice.
