### ISSUE TITLE
Hide Sidebar

### ISSUE THREAD

**Issue by justin3994** [sheodox/alexandrite#5]
Is there a way to hide the sidebar? It doesn't fit a 1080p vertical monitor with it included.

**Comment by sheodox** [comment]
Hey, thanks for the feature request. I just added this, there should be a button to toggle it in the top right corner now.

![image](https://github.com/sheodox/alexandrite/assets/3468630/4842c22f-1ab1-43e4-bb2b-04bfec0ab39f)
