### ISSUE TITLE
Multi platform Docker images

### ISSUE THREAD

**Issue by ismailkarsli** [sheodox/alexandrite#66]
I want to install this to my ARM server but it doesn't have ARM image. Can someone please add docker buildx to the CD? I really don't understand Github Actions to do this.

**Comment by ismailkarsli** [comment]
Voyager and MLMYM's pipelines seems easy. Can I PR this? @sheodox 
https://github.com/aeharding/voyager/blob/main/.github/workflows/docker.yml
https://github.com/rystaf/mlmym/blob/main/.github/workflows/docker.yml

**Comment by sheodox** [comment]
Closing this now, thanks again for the PR!
